<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AsignacionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('asignacion')->insert([
        	['id_profesor' => 1,
        	'id_asignatura' => 16,
        	'id_periodo' => 1,
        	'horas' => 72,
        	'subseccion_tecnica' => 'V-O10-N7-P3-C1',
        	'subseccion_practica' => 'NO',
        	'semestre' => 'N7',
        	'pensum' => 'P3',
        	'seccion' => 'C1',
        	'subseccion_campo_clinico' => ,
        	'jornada' => ''],

        	['id_profesor' => 1,
        	'id_asignatura' => 68,
        	'id_periodo' => 1,
        	'horas' => 72,
        	'subseccion_tecnica' => 'V-O20-N7-P3-C1',
        	'subseccion_practica' => 'NO',
        	'semestre' => 'N7',
        	'pensum' => 'P3',
        	'seccion' => 'C1',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => 'V'],

        	['id_profesor' => 1,
        	'id_asignatura' => 8,
        	'id_periodo' => 1,
        	'horas' => 72,
        	'subseccion_tecnica' => 'V-O10-N5-P3-C2',
        	'subseccion_practica' => 'NO',
        	'semestre' => 'N5',
        	'pensum' => 'P3',
        	'seccion' => 'C1',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => 'V'],

        	['id_profesor' => 2,
        	'id_asignatura' => 90,
        	'id_periodo' => 1,
        	'horas' => 72,
        	'subseccion_tecnica' => 'V-MI1-N4-P1-C1',
        	'subseccion_practica' => 'NO',
        	'semestre' => 'N4',
        	'pensum' => 'P1',
        	'seccion' => 'C1',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => 'V'],

        	['id_profesor' => 2,
        	'id_asignatura' => 95,
        	'id_periodo' => 1,
        	'horas' => 72,
        	'subseccion_tecnica' => 'V-MI1-N4-P1-C1',
        	'subseccion_practica' => 'NO',
        	'semestre' => 'N4',
        	'pensum' => 'P1',
        	'seccion' => 'C1',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => 'V'],

        	['id_profesor' => 2,
        	'id_asignatura' => 21,
        	'id_periodo' => 1,
        	'horas' => 54,
        	'subseccion_tecnica' => 'V-MI1-N4-P1-C1',
        	'subseccion_practica' => 'NO',
        	'semestre' => 'N4',
        	'pensum' => 'P1',
        	'seccion' => 'C1',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => 'V'],

        	['id_profesor' => 4,
        	'id_asignatura' => 21,
        	'id_periodo' => 1,
        	'horas' => 72,
        	'subseccion_tecnica' => 'V-O20-N5-P3-C1',
        	'subseccion_practica' => 'NO',
        	'semestre' => 'N5',
        	'pensum' => 'P3',
        	'seccion' => 'C1',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => 'V'],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],


        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        	['id_profesor' => ,
        	'id_asignatura' => ,
        	'id_periodo' => ,
        	'horas' => ,
        	'subseccion_tecnica' => '',
        	'subseccion_practica' => 'NO',
        	'semestre' => '',
        	'pensum' => '',
        	'seccion' => '',
        	'subseccion_campo_clinico' => 'NO',
        	'jornada' => ''],

        ]);
    }
}
